version: '1'

name: framework
services:
    framework:
        build: .
        working_dir: /var/www/
        restart: unless-stopped
        stdin_open: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "../:/var/www"
        networks:
            - backend
        depends_on:
            - mysql
            - selenium-hub
    mysql:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_PASSWORD: "root"
            MYSQL_DATABASE: 'root'
        volumes:
            - "./mysql/mysql_data:/var/lib/mysql"
        networks:
            - backend
    selenium:
        image: selenium/node-chrome:115.0-chromedriver-115.0
        shm_size: 2g
        depends_on:
            - selenium-hub
        networks:
            - backend
        environment:
            - SE_EVENT_BUS_HOST=selenium-hub
            - SE_EVENT_BUS_PUBLISH_PORT=4442
            - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
            - SE_NODE_OVERRIDE_MAX_SESSIONS=true
            - SE_NODE_MAX_SESSIONS=10
    selenium-hub:
        image: selenium/hub:latest
        container_name: selenium-hub
        ports:
            - "4442:4442"
            - "4443:4443"
            - "4444:4444"
        networks:
            - backend
networks:
    backend:
