version: '1'

services:
    framework:
        build: .
        working_dir: /var/www/
        restart: unless-stopped
        stdin_open: true
        volumes:
            - "../:/var/www"
        networks:
            - backend
    selenium:
        image: selenium/node-chrome:115.0-chromedriver-115.0
        shm_size: 2g
        depends_on:
            - selenium-hub
        networks:
            - backend
        environment:
            - SE_EVENT_BUS_HOST=selenium-hub
            - SE_EVENT_BUS_PUBLISH_PORT=4442
            - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
            - SE_NODE_OVERRIDE_MAX_SESSIONS=true
            - SE_NODE_MAX_SESSIONS=10
    selenium-hub:
        image: selenium/hub:latest
        container_name: selenium-hub
        ports:
            - "4442:4442"
            - "4443:4443"
            - "4444:4444"
        networks:
            - backend
networks:
    backend:
